### ISSUE TITLE
sentiment measurement in github review comments

### ISSUE THREAD

**Issue by sgzapata** [collab-uniba/Sentiment_Analysis_4SE_BERT#14]
Hello, I have a comments set from Github. Is there a notebook to measure sentiments from these comments?. THKS

**Comment by bateman** [comment]
see https://www.kaggle.com/lucamongelli/stackoverflow-w-bert
and https://www.kaggle.com/lucamongelli/jira-w-bert

**Comment by sgzapata** [comment]
👍
